# Generated by Django 5.2.4 on 2025-07-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_note_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('launch_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
